# Generated by Django 3.2.8 on 2023-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alumnoss'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=30)),
                ('codigocurso', models.CharField(max_length=30)),
                ('creditos', models.IntegerField()),
                ('fecharegistro', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
