# Generated by Django 3.2.8 on 2023-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichaalumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrealumno', models.CharField(max_length=30)),
                ('cursomatriculado', models.CharField(max_length=30)),
                ('correoalumno', models.CharField(max_length=40)),
                ('fecharegistro', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'fichaalumnos',
            },
        ),
    ]
