# Generated by Django 3.2.8 on 2023-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_fichaalumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrealumno', models.CharField(max_length=60)),
                ('cursomatriculado', models.CharField(max_length=60)),
                ('correoalumno', models.CharField(max_length=30)),
                ('fecharegistro', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
        migrations.AlterField(
            model_name='fichaalumnos',
            name='correoalumno',
            field=models.CharField(max_length=30),
        ),
    ]
