# Generated by Django 3.2.8 on 2023-04-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.alumnoss'),
        ),
    ]
